version: '3.7'

services:

  ui:
    container_name: ui
    build:
      context: https://github.com/Sander-N/User-Interface
      dockerfile: Dockerfile
    volumes:
      - '.:/User-Interface'
      - '/User-Interface/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true